server:
  port: 8080

spring:
  application:
    name: hello-service

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

grpc:
  client:
    exclamation-service:
      address: static://localhost:50001 # dapr sidecar gprc port
      negotiationType: PLAINTEXT