apiVersion: apps/v1
kind: Deployment
metadata:
  name: exclamation-service-deployment
spec:
  selector:
    matchLabels:
      app: exclamation-service
  template:
    metadata:
      annotations:
        dapr.io/app-id: exclamation-service
        dapr.io/app-port: "5000"
        dapr.io/enabled: "true"
        dapr.io/app-protocol: "grpc"
        dapr.io/log-level: "debug"
      labels:
        app: exclamation-service
        app.kubernetes.io/name: exclamation-service
        app.kubernetes.io/part-of: exclamation-service
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: exclamation-service
          image: docker.io/timlien/exclamation-service:1.0.0
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=75 -XX:TieredStopAtLevel=1"
            - name: PUBLIC_IP
              value: localhost:5000
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 5000