apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service-deployment
spec:
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      annotations:
        dapr.io/app-id: hello-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
        dpar.op/http-port: "8080"
      labels:
        app: hello-service
        app.kubernetes.io/name: hello-service
        app.kubernetes.io/part-of: hello-service
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: hello-service
          image: docker.io/timlien/hello-service:1.0.0
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=75 -XX:TieredStopAtLevel=1"
            - name: PUBLIC_IP
              value: localhost:8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-service
  ports:
    - port: 80
      targetPort: 8080